import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Shared/Header";
import Footer from "@/components/Shared/Footer";
import { AppKit } from "@/components/Context/AppKit";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "1Inch token swap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`layout ${inter.className}`}>
        <Header />
        <AppKit>
          <main className="content">{children}</main>
        </AppKit>
        <Footer />
      </body>
    </html>
  );
}
